#!/bin/bash
# Voxtype KDE Indicator - Installer
# Installs the overlay, indicator, and supporting config for voxtype on KDE Plasma 6 Wayland.
set -euo pipefail

REPO_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_DIR="$HOME/.local/bin"
SYSTEMD_DIR="$HOME/.config/systemd/user"
SHIMS_DIR="$HOME/.local/lib/voxtype-shims"

echo "=== Voxtype KDE Indicator Installer ==="
echo ""

# Check required dependencies
echo "Checking dependencies..."
missing=()
command -v voxtype >/dev/null 2>&1 || missing+=("voxtype")
# Check typelib availability without full import (avoids LD_PRELOAD requirement)
python3 -c "import gi; gi.require_version('Gtk', '4.0'); gi.require_version('Gtk4LayerShell', '1.0')" 2>/dev/null || missing+=("gtk4-layer-shell / python3-gobject")

if [ ${#missing[@]} -gt 0 ]; then
    echo "Missing required dependencies: ${missing[*]}"
    echo ""
    echo "Install with:"
    echo "  sudo dnf install gtk4-layer-shell python3-gobject"
    echo ""
    if [ -t 0 ]; then
        read -p "Continue anyway? [y/N] " -n 1 -r
        echo
        [[ $REPLY =~ ^[Yy]$ ]] || exit 1
    else
        echo "Run interactively to bypass, or install dependencies first."
        exit 1
    fi
fi

# Check optional dependencies
if ! python3 -c "from PyQt6.QtWidgets import QApplication" 2>/dev/null; then
    echo "  Note: PyQt6 not found (optional, needed for tray icon only)"
    echo "  Install with: pip install --user PyQt6"
fi

# Install scripts
echo "Installing scripts to $SCRIPTS_DIR..."
mkdir -p "$SCRIPTS_DIR"
install -m 755 "$REPO_DIR/scripts/voxtype-overlay" "$SCRIPTS_DIR/voxtype-overlay"
install -m 755 "$REPO_DIR/scripts/voxtype-indicator" "$SCRIPTS_DIR/voxtype-indicator"

# Install notify-send shim
echo "Installing notify-send shim to $SHIMS_DIR..."
mkdir -p "$SHIMS_DIR"
install -m 755 "$REPO_DIR/scripts/notify-send-shim" "$SHIMS_DIR/notify-send"

# Install systemd services
echo "Installing systemd services..."
mkdir -p "$SYSTEMD_DIR" "$SYSTEMD_DIR/voxtype.service.d"

# Resolve gtk4-layer-shell library path for LD_PRELOAD
# Can be overridden: LAYER_SHELL_LIB=/path/to/lib ./install.sh
LAYER_SHELL_LIB="${LAYER_SHELL_LIB:-}"
if [ -z "$LAYER_SHELL_LIB" ]; then
    # Auto-detect (skipped if user provided LAYER_SHELL_LIB)
    if command -v pkg-config >/dev/null 2>&1; then
        libdir=$(pkg-config --variable=libdir gtk4-layer-shell-0 2>/dev/null || true)
        if [ -n "$libdir" ] && [ -f "$libdir/libgtk4-layer-shell.so.0" ]; then
            LAYER_SHELL_LIB="$libdir/libgtk4-layer-shell.so.0"
        fi
    fi
fi
if [ -z "$LAYER_SHELL_LIB" ]; then
    # Fallback: search common paths
    for candidate in /usr/lib64/libgtk4-layer-shell.so.0 /usr/lib/libgtk4-layer-shell.so.0 /usr/lib/x86_64-linux-gnu/libgtk4-layer-shell.so.0; do
        if [ -f "$candidate" ]; then
            LAYER_SHELL_LIB="$candidate"
            break
        fi
    done
fi
if [ -z "$LAYER_SHELL_LIB" ]; then
    # Try ldconfig as last resort
    if command -v ldconfig >/dev/null 2>&1; then
        # Prefer native architecture (x86-64) to avoid multilib mismatch
        LAYER_SHELL_LIB=$(ldconfig -p 2>/dev/null | grep 'libgtk4-layer-shell.so.0 ' | grep -m1 'x86-64\|aarch64' | sed 's/.* => //' || true)
        # Fall back to first match if arch filter finds nothing
        if [ -z "$LAYER_SHELL_LIB" ]; then
            LAYER_SHELL_LIB=$(ldconfig -p 2>/dev/null | grep 'libgtk4-layer-shell.so.0 ' | head -1 | sed 's/.* => //' || true)
        fi
    fi
fi
if [ -z "$LAYER_SHELL_LIB" ] || [ ! -f "$LAYER_SHELL_LIB" ]; then
    echo "Error: could not find libgtk4-layer-shell.so.0 on this system."
    echo "Install it with: sudo dnf install gtk4-layer-shell"
    echo "Or specify the path: LAYER_SHELL_LIB=/path/to/lib ./install.sh"
    exit 1
fi

# Template the overlay service with the resolved library path
# Use awk to avoid sed metacharacter issues with the path
awk -v lib="$LAYER_SHELL_LIB" '{
    if ($0 ~ /^Environment=LD_PRELOAD=/) print "Environment=LD_PRELOAD=" lib
    else print
}' "$REPO_DIR/systemd/voxtype-overlay.service" > "$SYSTEMD_DIR/voxtype-overlay.service"
chmod 644 "$SYSTEMD_DIR/voxtype-overlay.service"

install -m 644 "$REPO_DIR/systemd/voxtype-indicator.service" "$SYSTEMD_DIR/"

# Generate the notify-send shim drop-in with a minimal safe PATH
SHIM_PATH="$HOME/.local/lib/voxtype-shims"
BASE_PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$HOME/.local/bin"
# Escape % to %% for systemd specifier expansion, strip any newlines
SAFE_PATH=$(printf '%s' "${SHIM_PATH}:${BASE_PATH}" | tr -d '\n' | sed 's/%/%%/g')
cat > "$SYSTEMD_DIR/voxtype.service.d/no-notify.conf" <<DROPIN
# Prepends the notify-send shim directory to intercept voxtype's
# hardcoded notify-send calls. Generated by install.sh with the
# user's PATH at install time.
[Service]
Environment="PATH=${SAFE_PATH}"
DROPIN
chmod 644 "$SYSTEMD_DIR/voxtype.service.d/no-notify.conf"

# Suppress "Remote desktop session started" notification
# Merges only the needed section instead of replacing the entire file
echo "Configuring KDE notification suppression..."
mkdir -p "$HOME/.config"
NOTIFYRC="$HOME/.config/xdg-desktop-portal-kde.notifyrc"
if command -v kwriteconfig6 >/dev/null 2>&1; then
    kwriteconfig6 --file "$NOTIFYRC" --group "Event/remotedesktopstarted" --key "Action" ""
    kwriteconfig6 --file "$NOTIFYRC" --group "Event/remotedesktopstarted" --key "Execute" ""
    kwriteconfig6 --file "$NOTIFYRC" --group "Event/remotedesktopstarted" --key "Logfile" ""
    kwriteconfig6 --file "$NOTIFYRC" --group "Event/remotedesktopstarted" --key "Sound" ""
    kwriteconfig6 --file "$NOTIFYRC" --group "Event/remotedesktopstarted" --key "TTS" ""
else
    # Fallback: deterministic rewrite — strip the target section if it exists,
    # then append the correct version. This avoids fragile in-place editing.
    SECTION="Event/remotedesktopstarted"
    if [ -f "$NOTIFYRC" ]; then
        # Remove the existing section (header through next header or EOF)
        awk -v sect="[$SECTION]" '
            BEGIN { skip=0 }
            /^\[/ { skip = ($0 == sect) ? 1 : 0 }
            !skip { print }
        ' "$NOTIFYRC" > "${NOTIFYRC}.tmp"
        mv "${NOTIFYRC}.tmp" "$NOTIFYRC"
    fi
    # Ensure trailing newline, then append the correct section
    [ -s "$NOTIFYRC" ] && [ -n "$(tail -c1 "$NOTIFYRC")" ] && printf '\n' >> "$NOTIFYRC"
    cat "$REPO_DIR/config/xdg-desktop-portal-kde.notifyrc" >> "$NOTIFYRC"
fi

# Reload and enable
echo "Enabling services..."
systemctl --user daemon-reload
systemctl --user enable --now voxtype-overlay.service

# Restart voxtype if running so the notify-send shim PATH takes effect
if systemctl --user is-active --quiet voxtype.service 2>/dev/null; then
    echo "Restarting voxtype.service to apply notification suppression..."
    systemctl --user restart voxtype.service
fi

echo ""
echo "=== Installation complete ==="
echo ""
echo "Services enabled:"
echo "  voxtype-overlay  - OSD overlay (GTK4 + layer-shell)"
echo ""
echo "Optional (not enabled by default):"
echo "  voxtype-indicator - System tray icon"
echo "  Enable with: systemctl --user enable --now voxtype-indicator.service"
